logging.level:
  org.springframework.web: INFO
  org.springframework.security: TRACE

spring.security:
  oauth2:
    client:
      registration:
        keycloak:
          scope: openid
          client-id: snowpiercerApi1
          authorization-grant-type: authorization_code
      provider:
        keycloak:
          issuer-uri: http://localhost:8380/realms/snowpiercer